const crypto = require("crypto");

function generateSlug(title) {
  return title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

const blockchainTopics = [
  "What is Blockchain Technology?",
  "How Smart Contracts Work",
  "Consensus Mechanisms Explained",
  "The Future of Decentralized Finance (DeFi)",
  "What is a Blockchain Node?",
  "Understanding Layer 2 Scaling Solutions",
  "The Role of Oracles in Blockchain",
  "Blockchain Security Best Practices",
  "Interoperability Between Blockchains",
  "How Proof of Stake Works",
  "What is a Decentralized Autonomous Organization (DAO)?",
  "Introduction to Non-Fungible Tokens (NFTs)",
  "How Layer 1 and Layer 2 Work Together",
  "Blockchain and Supply Chain Transparency",
  "What is a Rollup in Blockchain?",
  "The Impact of CBDCs on the Crypto Market",
  "What are zk-SNARKs and zk-Rollups?",
  "Decentralized Identity in Web3",
  "Blockchain in Healthcare: Use Cases",
  "Ethereum vs. Solana: A Technical Comparison",
  "Bitcoin Mining and Its Environmental Impact",
  "The Role of Validators in a Proof of Stake Network",
  "How to Secure Your Crypto Wallet",
  "Blockchain Governance Models Explained",
  "Why Interoperability Matters for Web3",
  "What is a Layer 0 Protocol?",
  "The Rise of Modular Blockchains",
  "Understanding Crypto Bridges and Their Risks",
  "Zero-Knowledge Proofs: A Deep Dive",
  "The Evolution of Token Standards (ERC-20, ERC-721, ERC-1155)",
  "How to Choose a Blockchain for Your Project",
  "What is MEV (Maximal Extractable Value)?",
  "Blockchain Sharding Explained",
  "The Importance of Cryptographic Hash Functions",
  "Bitcoin vs. Ethereum: Key Differences",
  "How DeFi Lending Platforms Work",
  "Understanding Crypto Staking and Yield Farming",
  "The Role of Rollups in Ethereum's Scalability Plan",
  "What is the Blockchain Trilemma?",
  "The Basics of Tokenomics",
  "Crypto Payment Gateways: How They Work",
  "How DAOs Are Changing Business Models",
  "The Future of Privacy Coins",
  "Blockchain-Based Voting Systems",
  "How to Build a dApp on Ethereum",
  "Decentralized Storage Solutions: IPFS and Filecoin",
  "The Role of Blockchain in Metaverse Development",
  "Ethereum Gas Fees Explained",
  "What is a Sidechain?",
  "The Advantages of Using a Hardware Wallet",
  "Why DeFi is the Future of Finance",
  "What are Cross-Chain Swaps?",
  "How Atomic Swaps Work",
  "The Evolution of Web3 Infrastructure",
  "The Ethics of AI and Blockchain Integration",
  "How to Run a Blockchain Node",
  "The Role of Blockchain in Gaming",
  "Decentralized Exchanges vs. Centralized Exchanges",
  "The Benefits of Using Layer 2 Scaling Solutions",
  "What is a Public vs. Private Blockchain?",
  "Understanding NFT Royalties",
  "The Growth of DAO Governance Tools",
  "How Blockchain is Transforming Digital Identity",
  "The Rise of Web3 Social Media Platforms",
  "The Security Risks in Smart Contracts",
  "What is a Rollup-as-a-Service (RaaS)?",
  "How Blockchain Enables Cross-Border Payments",
  "Understanding Multi-Party Computation (MPC)",
  "Blockchain Interoperability Protocols: Cosmos vs. Polkadot",
  "How Liquid Staking Works",
  "The Future of Institutional Crypto Adoption",
  "Understanding Blockchain API Integrations",
  "The Impact of Ethereum 2.0 on DeFi",
  "What is a DAO Treasury and How Does it Work?",
  "How to Participate in a Blockchain Testnet",
  "The Importance of Open Source in Blockchain Development",
  "Understanding Blockchain Data Indexing",
  "The Role of Decentralized Oracles in Web3",
  "How Crypto Wallets Enable On-Chain Interactions",
  "The Rise of Blockchain Gaming Guilds",
  "What is a Governance Token?",
  "Blockchain-Based Copyright Protection",
  "The Evolution of Stablecoins: Algorithmic vs. Collateralized",
  "The Intersection of AI and Blockchain",
  "What is a Smart Contract Auditor?",
  "How to Create a Custom Token on Ethereum",
  "The Role of Layer 3 in Blockchain Architecture",
  "The Security Implications of Bridge Hacks",
  "The Concept of On-Chain Reputation Systems",
  "Understanding Blockchain Forensics",
  "The Economics of Running a Validator Node",
  "How to Build a Cross-Chain dApp",
  "The Importance of Decentralized Governance in Web3",
  "What is a Wrapped Token?",
  "The Evolution of Web3 Search Engines",
  "Understanding the Blockchain Consensus Landscape",
  "How to Launch a Token on Solana",
  "Blockchain-Based Intellectual Property Management",
  "The Role of Quantum Computing in Blockchain Security",
  "What is an NFT Marketplace?",
  "The Adoption of Blockchain in Real Estate",
  "What is a Self-Sovereign Identity?",
  "How DAOs are Disrupting Traditional Organizations",
  "The Role of GameFi in Web3 Adoption",
  "What is a Decentralized Storage Network?"
];

const sampleData = blockchainTopics.slice(0, 100).map((title, index) => ({
  id: crypto.randomUUID(),
  title,
  slug: generateSlug(title),
  metaDescription: `Learn about ${title.toLowerCase()} and how it impacts blockchain infrastructure and Web3 technology.`,
  content: `This article delves into the topic of ${title}, explaining its significance, use cases, and impact on the blockchain ecosystem.`
}));

console.log(JSON.stringify(sampleData, null, 2));
